# Generated by Django 5.0.3 on 2024-06-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimplePage',
            new_name='MainPage',
        ),
    ]
