# Generated by Django 5.0.3 on 2024-06-27 16:20

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_simplepage_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='header_image',
            field=image_cropping.fields.ImageCropField(upload_to='media/header_images/'),
        ),
    ]
