# Generated by Django 5.0.3 on 2024-06-27 16:42

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_mainpage_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('header_image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
